# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x0cuser_service\"%\n\x12GetStudentsRequest\x12\x0f\n\x07user_id\x18\x01 \x03(\x05\">\n\x13GetStudentsResponse\x12\'\n\x08students\x18\x01 \x03(\x0b\x32\x15.user_service.Student\"y\n\x07Student\x12\x12\n\nstudent_id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\r\n\x05grade\x18\x05 \x01(\x05\x12\x15\n\racademic_year\x18\x06 \x01(\t\"$\n\x11GetTeacherRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"^\n\x12GetTeacherResponse\x12\x12\n\nteacher_id\x18\x02 \x01(\x05\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\"*\n\x17GetStudentByUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"B\n\x18GetStudentByUserResponse\x12&\n\x07student\x18\x01 \x01(\x0b\x32\x15.user_service.Student\"E\n\x1dGetStudentsByGradeYearRequest\x12\r\n\x05grade\x18\x01 \x01(\x05\x12\x15\n\racademic_year\x18\x02 \x01(\t\"I\n\x1eGetStudentsByGradeYearResponse\x12\'\n\x08students\x18\x01 \x03(\x0b\x32\x15.user_service.Student2\x99\x03\n\x0bUserService\x12W\n\x10GetStudentsByIds\x12 .user_service.GetStudentsRequest\x1a!.user_service.GetStudentsResponse\x12W\n\x12GetTeacherByUserId\x12\x1f.user_service.GetTeacherRequest\x1a .user_service.GetTeacherResponse\x12\x63\n\x12GetStudentByUserId\x12%.user_service.GetStudentByUserRequest\x1a&.user_service.GetStudentByUserResponse\x12s\n\x16GetStudentsByGradeYear\x12+.user_service.GetStudentsByGradeYearRequest\x1a,.user_service.GetStudentsByGradeYearResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSTUDENTSREQUEST']._serialized_start=36
  _globals['_GETSTUDENTSREQUEST']._serialized_end=73
  _globals['_GETSTUDENTSRESPONSE']._serialized_start=75
  _globals['_GETSTUDENTSRESPONSE']._serialized_end=137
  _globals['_STUDENT']._serialized_start=139
  _globals['_STUDENT']._serialized_end=260
  _globals['_GETTEACHERREQUEST']._serialized_start=262
  _globals['_GETTEACHERREQUEST']._serialized_end=298
  _globals['_GETTEACHERRESPONSE']._serialized_start=300
  _globals['_GETTEACHERRESPONSE']._serialized_end=394
  _globals['_GETSTUDENTBYUSERREQUEST']._serialized_start=396
  _globals['_GETSTUDENTBYUSERREQUEST']._serialized_end=438
  _globals['_GETSTUDENTBYUSERRESPONSE']._serialized_start=440
  _globals['_GETSTUDENTBYUSERRESPONSE']._serialized_end=506
  _globals['_GETSTUDENTSBYGRADEYEARREQUEST']._serialized_start=508
  _globals['_GETSTUDENTSBYGRADEYEARREQUEST']._serialized_end=577
  _globals['_GETSTUDENTSBYGRADEYEARRESPONSE']._serialized_start=579
  _globals['_GETSTUDENTSBYGRADEYEARRESPONSE']._serialized_end=652
  _globals['_USERSERVICE']._serialized_start=655
  _globals['_USERSERVICE']._serialized_end=1064
# @@protoc_insertion_point(module_scope)
