version: "3.9"
services:
  user_service:
    build: ./user_service
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq

  exam_service:
    build: ./exam_service
    ports:
      - "8002:8000"
    depends_on:
      - rabbitmq

  notification_service:
    build: ./notification_service
    ports:
      - "8003:8000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # main AMQP port
      - "15672:15672"   # management UI