# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: exam.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'exam.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nexam.proto\x12\x05\x65xams\"\x07\n\x05\x45mpty\"\x1e\n\x0b\x45xamRequest\x12\x0f\n\x07\x65xam_id\x18\x01 \x01(\x05\"g\n\x11\x43reateExamRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\x10\n\x08\x64uration\x18\x04 \x01(\x05\x12\x12\n\nteacher_id\x18\x05 \x01(\x05\"s\n\x0c\x45xamResponse\x12\x0f\n\x07\x65xam_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07subject\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x10\n\x08\x64uration\x18\x05 \x01(\x05\x12\x12\n\nteacher_id\x18\x06 \x01(\x05\"7\n\x11ListExamsResponse\x12\"\n\x05\x65xams\x18\x01 \x03(\x0b\x32\x13.exams.ExamResponse\"6\n\x12\x43reateExamResponse\x12\x0f\n\x07\x65xam_id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"8\n\x11\x41ssignExamRequest\x12\x0f\n\x07\x65xam_id\x18\x01 \x01(\x05\x12\x12\n\nstudent_id\x18\x02 \x03(\x05\"%\n\x12\x41ssignExamResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"$\n\x0eStudentRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\x05\"$\n\x0eTeacherRequest\x12\x12\n\nteacher_id\x18\x01 \x01(\x05\"4\n\x12\x41ttemptExamRequest\x12\x0f\n\x07\x65xam_id\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x05\"&\n\x13\x41ttemptExamResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xce\x03\n\x0b\x45xamService\x12\x32\n\x07GetExam\x12\x12.exams.ExamRequest\x1a\x13.exams.ExamResponse\x12\x33\n\tListExams\x12\x0c.exams.Empty\x1a\x18.exams.ListExamsResponse\x12\x41\n\nCreateExam\x12\x18.exams.CreateExamRequest\x1a\x19.exams.CreateExamResponse\x12\x41\n\nAssignExam\x12\x18.exams.AssignExamRequest\x1a\x19.exams.AssignExamResponse\x12\x44\n\x11GetExamsByStudent\x12\x15.exams.StudentRequest\x1a\x18.exams.ListExamsResponse\x12\x44\n\x11GetExamsByTeacher\x12\x15.exams.TeacherRequest\x1a\x18.exams.ListExamsResponse\x12\x44\n\x0b\x41ttemptExam\x12\x19.exams.AttemptExamRequest\x1a\x1a.exams.AttemptExamResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exam_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=21
  _globals['_EMPTY']._serialized_end=28
  _globals['_EXAMREQUEST']._serialized_start=30
  _globals['_EXAMREQUEST']._serialized_end=60
  _globals['_CREATEEXAMREQUEST']._serialized_start=62
  _globals['_CREATEEXAMREQUEST']._serialized_end=165
  _globals['_EXAMRESPONSE']._serialized_start=167
  _globals['_EXAMRESPONSE']._serialized_end=282
  _globals['_LISTEXAMSRESPONSE']._serialized_start=284
  _globals['_LISTEXAMSRESPONSE']._serialized_end=339
  _globals['_CREATEEXAMRESPONSE']._serialized_start=341
  _globals['_CREATEEXAMRESPONSE']._serialized_end=395
  _globals['_ASSIGNEXAMREQUEST']._serialized_start=397
  _globals['_ASSIGNEXAMREQUEST']._serialized_end=453
  _globals['_ASSIGNEXAMRESPONSE']._serialized_start=455
  _globals['_ASSIGNEXAMRESPONSE']._serialized_end=492
  _globals['_STUDENTREQUEST']._serialized_start=494
  _globals['_STUDENTREQUEST']._serialized_end=530
  _globals['_TEACHERREQUEST']._serialized_start=532
  _globals['_TEACHERREQUEST']._serialized_end=568
  _globals['_ATTEMPTEXAMREQUEST']._serialized_start=570
  _globals['_ATTEMPTEXAMREQUEST']._serialized_end=622
  _globals['_ATTEMPTEXAMRESPONSE']._serialized_start=624
  _globals['_ATTEMPTEXAMRESPONSE']._serialized_end=662
  _globals['_EXAMSERVICE']._serialized_start=665
  _globals['_EXAMSERVICE']._serialized_end=1127
# @@protoc_insertion_point(module_scope)
