# Generated by Django 5.2.6 on 2025-09-16 03:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_message', models.TextField()),
                ('log_type', models.CharField(choices=[('info', 'Info'), ('error', 'Error'), ('warning', 'Warning')], default='info', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
            ],
        ),
    ]
