# Generated by Django 5.2.6 on 2025-09-16 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transactionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlog',
            name='payment',
        ),
    ]
