# Generated by Django 5.2.6 on 2025-09-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='teacher',
            new_name='teacher_id',
        ),
    ]
