# Generated by Django 5.2.6 on 2025-09-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_rename_teacher_exam_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examassignment',
            name='student',
        ),
        migrations.AddField(
            model_name='examassignment',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
