# Generated by Django 5.2.6 on 2025-09-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_examassignment_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexamattempt',
            name='student',
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
